version: "3.8"
services:

  mongodb:
    image : mongo
    container_name: mongodb
    # command: [--auth]
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=DB_USER
      # - MONGO_INITDB_ROOT_PASSWORD=DB_PASS
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - /home/front/repo-fc/nodejs-aulas/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dbpg
      PGDATA: /data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: